### ISSUE TITLE
Faraday 1.0.0

### ISSUE THREAD

**Issue by macharmi** [zendesk/basecrm-ruby#75]
Hey team,

Is it possible to upgrade `basecrm-ruby` dependencies to use `faraday` gem version `1.0.0`?

I already created a [pull request](https://github.com/zendesk/basecrm-ruby/pull/74).

Best regards,
Mohamed.

**Comment by struniu** [comment]
It was done in https://github.com/zendesk/basecrm-ruby/pull/82 Closing

**Comment by macharmi** [comment]
Thank you
